### ISSUE TITLE
Rate :) 

### ISSUE THREAD

**Issue by lnxpy** [frowzyispenguin/aloodak#1]
wow.. 😃
It could be so vital for people from Tehran.. 
Improve it and make it better.. 😃🥇

Good Luck 🤞
lnxpy

**Comment by frowzyispenguin** [comment]
oh bro u scared me .. i thought it have really issues :laughing: 
tnx .. 
tryana to add new cities such as isfihan , mahshad and shiraz if data sheets exists :)
